### ISSUE TITLE
Old IRD data issues (IRD with a 20 cm telescope)

### ISSUE THREAD

**Issue by HajimeKawahara** [prvjapan/pyird#80]
I am now analyzing the Jupiter data as observed by IRD with a 20cm telescope (very old data) and found some issues:

- 1. One needs to rotate the detector image in 90 degree to match to the current setting
- 2. There are some zero stripes in the detector images. The width is 2 pixel and the interval is 128 pixels.

$$ j = k + 128 i  $$

for 

$$ k \in (63, 64), i = 0, 1, \cdots, 15 $$

![Figure_1](https://github.com/prvjapan/pyird/assets/15956904/2c3f1dee-3c0e-48c1-a172-6802353965db)

The issue 2 prevents `aptrace`. This can be solved by filling the zeros rows by nearby rows, i.e. 63 by 62, 64 by 65. 

- nap is 21 for H, i.e. only star fiber

**Comment by HajimeKawahara** [comment]
`mmf1` and `mmf2` in `trace_mmf` are confusing. I propose to rename them (in the next PR).

**Comment by HajimeKawahara** [comment]
![Figure_1](https://github.com/prvjapan/pyird/assets/15956904/79e428c6-c5fc-45eb-89ca-038b95d50f0d)

something wrong...

**Comment by YuiKasagi** [comment]
I found this issue was caused by two factors:
1. The rotation of image was only applied to Flat image
2. Need 90 degree rotation and y-axis inversion -- without inversion, identification of Th-Ar emission line will be failed.

I confirmed that the pipeline works with manually rotated images (not yet implementing rotation instance in irdstream). This figure compares spectra from images applied rotation and rotation + inversion. Telluric lines show that the latter (rotation+inversion) is correct.
![image](https://github.com/prvjapan/pyird/assets/66584422/452fc0c8-5c83-46fc-9c00-a543c9adbbac)

![スクリーンショット 2024-05-13 17 37 54](https://github.com/prvjapan/pyird/assets/66584422/ee0c79aa-9adf-4c05-b0c3-f2b228876d4a)

**Comment by HajimeKawahara** [comment]
Thank you! I see, I will try to implement (and refactor) those part.

**Comment by HajimeKawahara** [comment]
![Figure_1](https://github.com/prvjapan/pyird/assets/15956904/f921bdd6-5317-412e-8745-ad60756b17e6)

reproduced! Note that the inverse is 0-th axis. (y=0, x=1?)

**Comment by HajimeKawahara** [comment]
![Figure_1](https://github.com/prvjapan/pyird/assets/15956904/18091f39-0b4e-4bcb-9596-334038cd18e0)
